package LexicalAnalyzer;

public enum TokenType {
    // Palavras-chave
    PROGRAMA, VAR, INTEIRO, BOOLEANO, PROCEDIMENTO, FUNCAO, INICIO, FIM,
    SE, ENTAO, SENAO, ENQUANTO, FACA, LEIA, ESCREVA, RETORNO, BREAK, CONTINUE,
    VERDADEIRO, FALSO, NAO, OU, E,

    // Operadores e Símbolos
    ATRIBUICAO, IGUAL, DIFERENTE, MENOR, MENOR_IGUAL, MAIOR, MAIOR_IGUAL,
    MAIS, MENOS, MULT,
    PONTO_E_VIRGULA, VIRGULA, ABRE_PAREN, FECHA_PAREN, PONTO, DOIS_PONTOS, DIVISAO,

    // Literais
    ID, NUMERO,

    // Outros
    FIM_ARQUIVO,
    ERRO
}
